### ISSUE TITLE
Feature/Setup Azure Storage Emulator using Docker

### ISSUE THREAD

**Issue by faraonc** [hwsc-org/hwsc-file-transaction-svc#29]
## Description
As a developer, I want to be able to unit test Azure Blob Storage locally

## Definitions of Done
- [x] Install Docker locally
- [x] Learn Docker https://docker-curriculum.com/
~- [ ] Run Azure Blob Storage from https://hub.docker.com/r/microsoft/azure-storage-emulator/~
- [x] Verify Azurite can do our job to emulate and run Azure Blob Storage as dev https://github.com/azure/azurite
- [x] Update README.md

**Comment by acltang** [comment]
Will update wiki and README.md
