### ISSUE TITLE
Test/GetStatus without Synchronization

### ISSUE THREAD

**Issue by faraonc** [hwsc-org/hwsc-file-transaction-svc#32]
## Description
I want to test GetStatus without Synchronization, and modify codes as needed.
https://github.com/hwsc-org/hwsc-file-transaction-svc/issues/30

## Definitions of Done
- [x] Unit test with code coverage
- [x] determine where to declare the variable `state` to persist the value properly
- [ ] integration test with hwsc-api-blocks

**Comment by acltang** [comment]
Closing in favor of https://github.com/hwsc-org/hwsc-file-transaction-svc/issues/33
