### ISSUE TITLE
Test/Check Azure Blob Storage in GetStatus

### ISSUE THREAD

**Issue by faraonc** [hwsc-org/hwsc-file-transaction-svc#33]
## Description
https://github.com/hwsc-org/hwsc-file-transaction-svc/issues/31

As a user, I want to test Check Azure Blob Storage in GetStatus

## Definitions of Done
- [x] unit test
- [x] integration test `hwsc-api-bloks`

**Comment by acltang** [comment]
- [ ] Test whether Azurite is running
- [ ] Test if there is a built-in timeout/ping function
- [ ] Upload file and test if file exists
- [ ] Add read/write mutex to the service state variable

https://github.com/hwsc-org/hwsc-document-svc/blob/master/service/service.go#L78
