### ISSUE TITLE
Feature/CI-CD pipeline

### ISSUE THREAD

**Issue by faraonc** [hwsc-org/hwsc-file-transaction-svc#37]
## Description
As a developer, I want to implement CI-CD pipeline with Azure DevOps and Docker Hub

## Definitions of Done
- [x] Dockerfile
- [x] DockerHub repo
- [x] Azure DevOps yml file
- [x] A successful build

**Comment by acltang** [comment]
'docker run -t -p 10000:10000 -p 10001:10001 -p 10002:10002 -v ~/azurite:/opt/azurite/folder arafato/azurite'

**Comment by faraonc** [comment]
In the unit test section:
1. `docker pull arafato/azurite`
2. `docker run -t -p 10000:10000 -p 10001:10001 -p 10002:10002 -v ~/azurite:/opt/azurite/folder arafato/azurite` . I think `-d` will run it in the background

**Comment by faraonc** [comment]
https://hwsc-org.github.io/wikis/fundamentals/ci-cd.html
