### ISSUE TITLE
Feature/Research AWS file storage service

### ISSUE THREAD

**Issue by faraonc** [hwsc-org/hwsc-file-transaction-svc#61]
## Description
As a user, I want to store my binary files in AWS file storage service.

## Definitions of Done
- [x] a research about an AWS equivalence of Azure Blob Storage.

There is a lot of AWS cloud services, but I recommend starting with S3. 
What we are looking for is a cloud service that allows user to download. display, and play files from the browser. We might need to use a CDN as well.

**Comment by faraonc** [comment]
worth checking out

https://learnetto.com/blog/tutorial-how-to-use-amazon-s3-and-cloudfront-cdn-to-serve-images-fast-and-cheap

**Comment by yeseulan** [comment]
https://dluo.me/s3databoto3

**Comment by yeseulan** [comment]
https://realpython.com/python-boto3-aws-s3/
